### PR TITLE
:fire: remove extra server for assets

### LINKED ISSUE #69: build image on Dockerhub
If we can get rid of the proxy container we can let this build automatically on Dockerhub.

### PR DESCRIPTION
**Pull request by nomaster**
Rails now handles the serving of assets (static files), so we remove the
extra Nginx container and its configuration.

fixes #69

### CODE REVIEW

**Comment by nomaster** [comment]
I amended the commit, because the redirects didn't work as expected. Should be fine now.

**Comment by nomaster** [comment]
For development, I suggest starting the program like this:
```docker-compose run -p 8080:80 backend ```
In production, there will probably be an ingress service binding to the host port 80 and connecting to the backend over some internal network. Therefore, I recommend no to specify it here.

**Comment by YtvwlD** [comment]
Everything seems to work, so I think we can merge this.

I'm not entirely sure how to get this running on our dockerserver, but it should be possible.

**Comment by nomaster** [comment]
I recommend Træfik. If you want, I can create another project that suits our needs

**Pull request merged**
