### PR TITLE
API V2 

### PR DESCRIPTION
**Pull request by marudor**
Reference: https://github.com/Space-Market/API
Implementation still meh :/
But knows both v1 and v2 now.
Frontend uses v2 for deposit/payment to get rid of modifying GETs

### CODE REVIEW

**Comment by nomaster** [comment]
@marudor please resolve conflict

**Comment by nomaster** [comment]
Docker build fails, because JavaScript runtime is supposedly missing

**Comment by YtvwlD** [comment]
This PR does many more things than just adding support for v1 and v2. Is it possible to split this in smaller ones?

**Comment by YtvwlD** [comment]
I'm trying to pick a few of the changes and rebase the remaining ones. Please don't merge just yet.

**Pull request closed without merging**
